site_name: flumine
site_description: Trading framework for Betfair API-NG.

theme:
    name: 'material'

    palette:
      primary: 'blue grey'
      accent: 'indigo'

    features:
      - navigation.tabs
      - navigation.tabs.sticky

repo_name: liampauling/flumine
repo_url: https://github.com/liampauling/flumine
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Getting started:
      - QuickStart: 'quickstart.md'
      - Help: 'help.md'
    - Advanced:
      - Clients: 'clients.md'
      - Strategies: 'strategies.md'
      - Trades / Orders: 'trades.md'
      - Markets: 'markets.md'
      - Controls: 'controls.md'
      - Workers: 'workers.md'
      - Sports Data: 'sportsdata.md'
      - Advanced Usage: 'advanced.md'
      - Performance: 'performance.md'
      - Architecture: 'architecture.md'

markdown_extensions:
  - admonition
  - codehilite
